### ISSUE TITLE
Use relative path

### ISSUE THREAD

**Issue by ghost** [AqibMiah/A-level-Coursework-nea#1]
https://github.com/AqibMiah/A-level-Coursework-nea/blob/12f7f8d82bf883667776d00026c4be4cb4960adb/main.py#L98

Use relative paths, not absolute:

Try `~/Downloads` this will mean the program can be run on any device, currently only your user is able to run it.

**Comment by ghost** [comment]
plt.savefig(os.path.expanduser(f'~/Downloads/{fileName}'))

**Comment by AqibMiah** [comment]
Thank you polarian i have resolved this!
